# Generated by Django 6.0.4 on 2026-06-23 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.FileField(blank=True, null=True, upload_to='viajes/')),
                ('destino', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('concluido', 'Concluido')], max_length=20)),
                ('departamento', models.CharField(choices=[('ventas', 'Ventas'), ('soporte', 'Soporte'), ('direccion', 'Dirección')], max_length=20)),
                ('requiere_anticipo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='recibos/')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_gasto', models.CharField(choices=[('hospedaje', 'Hospedaje'), ('alimentacion', 'Alimentación'), ('transporte', 'Transporte')], max_length=20)),
                ('fecha_emision', models.DateField()),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='viajes.viaje')),
            ],
        ),
    ]
